apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: default
  labels:
    app: products
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: product-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
